version: '3'
services:
  app1:
    environment: 
      - URLAPP2=http://app2/post
      - AUTH=http://auth/auth
    image: colabdevops/app1:latest
    container_name: app1
    ports:
      - "8081:80"
    networks:
      - prod-network
  app2:
    environment: 
      - URLAPP2=http://app1/post
      - AUTH=http://auth/auth
    image: colabdevops/app2:latest
    container_name: app2
    ports:
      - "8082:80"
    networks:
      - prod-network
  auth:
    image: colabdevops/auth:latest
    container_name: auth
    ports:
      - "8083:80"
    networks:
      - prod-network
networks:
  prod-network:
    driver: bridge